version: '3.8'

services:
    ffbeequip:
        build:
            context: .
        restart: always
        environment:
            - ENV=production
            - PORT=3000
        volumes:
            - ./GL/corrections.json:/ffbeEquip/static/GL/corrections.json
            - ./JP/corrections.json:/ffbeEquip/static/JP/corrections.json
            - ./config.json:/ffbeEquip/.config.json
        ports:
            - 3000:3000
